apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: qs-project
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/Siddhi1708/kubernetes-qst.git'
    targetRevision: main
    path: k8s
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
