apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  labels:
    app: prometheus
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: 'springboot'
        metrics_path: /actuator/prometheus
        static_configs:
          - targets: ['springboot-service:8080']
        basic_auth:
          username: 'admin'
          password: 'admin123'

      - job_name: 'frontend'
        static_configs:
          - targets: ['frontend-service.default.svc.cluster.local:80']
